export const floors = [
    {
      number: 1,
      rooms: [
        { number: 101, can_hold: 1, type: "فردية", bookings: {} },
        { number: 102, can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 103, can_hold: 2, type: "ثنائية", bookings: {} },
        { number: 104, can_hold: 4, type: "رباعية (سرير كبير)", bookings: {} },
        { number: 105, can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 106, can_hold: 3, type: "ثلاثية", bookings: {} },
        { number: 107, can_hold: 3, type: "ثلاثية", bookings: {} },
      ],
    },
    {
      number: 2,
      rooms: [
        { number: 201, can_hold: 4 , type: "رباعية (سرير كبير)", bookings: {} },
        { number: 202, can_hold: 3 , type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 203, can_hold: 3 , type: "ثلاثية", bookings: {} },
        { number: 204, can_hold: 3 , type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 205, can_hold: 1 , type: "فردية", bookings: {} },
        { number: 206, can_hold: 1 , type: "فردية", bookings: {} },
        { number: 207, can_hold: 3 , type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 208, can_hold: 2 , type: "ثنائية", bookings: {} },
        { number: 209, can_hold: 5 , type: "خماسية (سرير كبير)", bookings: {} },
        { number: 210, can_hold: 2 , type: "ثنائية", bookings: {} },
        { number: 211, can_hold: 3 , type: "ثلاثية", bookings: {} },
        { number: 212, can_hold: 4 , type: "رباعية (سرير كبير)", bookings: {} },
        { number: 213, can_hold: 2 , type: "ثنائية", bookings: {} },
        { number: 214, can_hold: 3 , type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 215, can_hold: 4 , type: "رباعية (سرير كبير)", bookings: {} },
      ],
    },
    {
      number: 3,
      rooms: [
        { number: 301,can_hold: 4, type: "رباعية (سرير كبير)", bookings: {} },
        { number: 302,can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 303,can_hold: 3, type: "ثلاثية", bookings: {} },
        { number: 304,can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 305,can_hold: 1, type: "فردية", bookings: {} },
        { number: 306,can_hold: 1, type: "فردية", bookings: {} },
        { number: 307,can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 308,can_hold: 2, type: "ثنائية", bookings: {} },
        { number: 309,can_hold: 3, type: "ثلاثية", bookings: {} },
        { number: 310,can_hold: 2, type: "ثنائية", bookings: {} },
        { number: 311,can_hold: 3, type: "ثلاثية", bookings: {} },
        { number: 312,can_hold: 4, type: "رباعية (سرير كبير)", bookings: {} },
        { number: 313,can_hold: 2, type: "ثنائية", bookings: {} },
        { number: 314,can_hold: 3, type: "ثلاثية (سرير كبير)", bookings: {} },
        { number: 315,can_hold: 4, type: "رباعية (سرير كبير)", bookings: {} },
      ],
    },
    {
      number: 4,
      rooms: [
        { number: 401,can_hold: 6, type: "سكن", bookings: {} },
        { number: 405,can_hold: 6, type: "سكن", bookings: {} },
        { number: 408,can_hold: 6, type: "سكن", bookings: {} },
  ],
    },
  ]